FROM quay.io/jupyter/datascience-notebook
WORKDIR /home/jovyan
RUN rmdir work
RUN mkdir 3DEP_demo_files
COPY dockerfiles/notebooks/*.ipynb ./3DEP_demo_files/
RUN git clone https://github.com/OpenTopography/OT_3DEP_Workflows.git
