FROM python:3.9-slim

WORKDIR /app

COPY start_workflow_api/requirements.txt /app/

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY start_workflow_api/main.py /app/

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8084"]

